# Generated by Django 4.1.7 on 2023-05-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arty', '0002_delete_membre_remove_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('cv', models.FileField(upload_to=None)),
                ('photo', models.ImageField(upload_to=None)),
                ('linkedin', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Equipe',
        ),
    ]
