# Generated by Django 4.1.7 on 2023-05-23 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arty', '0003_personne_delete_equipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_creation',
            new_name='date_debut',
        ),
        migrations.RemoveField(
            model_name='project',
            name='temoignage',
        ),
        migrations.AddField(
            model_name='project',
            name='date_fin',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('En Cours', 'En Cours'), ('Demandé', 'Demandé'), ('Achevé', 'Achevé')], default='Demandé', max_length=50),
        ),
    ]
