# Generated by Django 4.1.7 on 2023-05-23 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arty', '0004_rename_date_creation_project_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_debut',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Demandé', 'Demandé'), ('Achevé', 'Achevé'), ('En Cours', 'En Cours')], default='Demandé', max_length=50),
        ),
    ]
