# Generated by Django 4.1.7 on 2023-05-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arty', '0005_alter_project_date_debut_alter_project_date_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Achevé', 'Achevé'), ('Demandé', 'Demandé'), ('En Cours', 'En Cours')], default='Demandé', max_length=50),
        ),
    ]
